"""initial_full_schema

Revision ID: a40ac7e58d63
Revises: 
Create Date: 2026-01-17 22:59:56.983962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a40ac7e58d63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel'), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=True),
    sa.Column('funcName', sa.String(), nullable=True),
    sa.Column('lineNo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('OHLCV',
    sa.Column('id_OHLCV', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('exchange_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_OHLCV')
    )
    op.create_index(op.f('ix_OHLCV_close_time'), 'OHLCV', ['close_time'], unique=False)
    op.create_index(op.f('ix_OHLCV_open_time'), 'OHLCV', ['open_time'], unique=False)
    op.create_index(op.f('ix_OHLCV_symbol'), 'OHLCV', ['symbol'], unique=False)
    op.create_table('IndicatorTechnique',
    sa.Column('id_IndiTech', sa.Integer(), nullable=False),
    sa.Column('OHLCV_ID', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('RSI', sa.Float(), nullable=False),
    sa.Column('MACD', sa.Float(), nullable=False),
    sa.Column('MA', sa.Float(), nullable=False),
    sa.Column('VWAP', sa.Float(), nullable=False),
    sa.Column('BollingerBands', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['OHLCV_ID'], ['OHLCV.id_OHLCV'], ),
    sa.PrimaryKeyConstraint('id_IndiTech')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('IndicatorTechnique')
    op.drop_index(op.f('ix_OHLCV_symbol'), table_name='OHLCV')
    op.drop_index(op.f('ix_OHLCV_open_time'), table_name='OHLCV')
    op.drop_index(op.f('ix_OHLCV_close_time'), table_name='OHLCV')
    op.drop_table('OHLCV')
    op.drop_table('Logs')
    # ### end Alembic commands ###
